export const MOVE = 'MOVE'
export const START = 'START'
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS'
export const DROP = 'DROP'
export const ROTATE = 'ROTATE'
export const FLOOR_DROP = 'FLOOR_DROP'
export const COLOR_LINES = 'COLOR_LINES'